CVS_PATH = 'C:/Users/lasts/projects/prog-instruments-labs/lab_3/3.csv'
RESULT_PATH = 'C:/Users/lasts/projects/prog-instruments-labs/lab_3/result.json'

VALID_EMAIL_REGEX = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,}$'
VALID_HEIGHT_REGEX = r'^[1-2].d{2}$'
VALID_SNILS_REGEX = r'^d{11}$'
VALID_PASSPORT_REGEX = r'^d{2} d{2} d{6}$'
VALID_OCCUPATION_REGEX = r'^[ws]+$'
VALID_LONGITUDE_REGEX = r'^-?d+.d+$'
VALID_HEX_COLOR_REGEX = r'^#[0-9a-fA-F]{6}$'
VALID_ISSN_REGEX = r'^d{4}-d{4}$'
VALID_LOCALE_CODE_REGEX = r'^[a-z]{2,3}(-[a-z]{2})?$'
VALID_TIME_REGEX = r'^(?:2[0-3]|[0-1]d):[0-5]d:[0-5]d.d{6}$'
